name: Install Module And Cache

description: Setup Environment Variables for Django Project

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: bash

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
