name: Install Module And Cache

description: Setup Environment Variables for Django Project

runs:
  using: composite
  steps:
    - name: Run Corepack
      shell: bash
      run: corepack enable

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
