openapi: 3.0.2

info:
  title: Sample
  description: |-
    this is sample
  version: 1.0.0

tags:
  - name: user
    description: ""

paths:
  /me:
    get:
      description: ""
      tags:
        - user
      responses:
        "200":
          $ref: "#/components/responses/ValidUser"
        "400":
          $ref: "#/components/responses/BadRequest"

  /login:
    post:
      description: ""
      tags:
        - auth
      requestBody:
        $ref: "#/components/requestBodies/Login"
      responses:
        "201":
          $ref: "#/components/responses/LoginSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"

  /books:
    get:
      description: ""
      tags:
        - book
      parameters:
        - in: query
          name: title
          schema:
            type: string
        - in: query
          name: date-from
          schema:
            type: string
        - in: query
          name: date-to
          schema:
            type: string

      responses:
        "200":
          $ref: "#/components/responses/BookSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"

    post:
      tags:
        - book
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/Book"
      responses:
        "200":
          $ref: "#/components/schemas/Book"
        "400":
          $ref: "#/components/responses/BadRequest"

  /books/{id}:
    get:
      tags:
        - book
      description: ""
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true

      responses:
        "200":
          $ref: "#/components/responses/BookSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"

    put:
      tags:
        - book
      description: ""
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true

      requestBody:
        required: true
        $ref: "#/components/requestBodies/Book"

      responses:
        "200":
          $ref: "#/components/schemas/Book"
        "400":
          $ref: "#/components/responses/BadRequest"

components:
  schemas:
    Id:
      type: object
      required:
        - id
      properties:
        id:
          type: string

    Email:
      type: object
      properties:
        email:
          type: string

    Password:
      type: object
      properties:
        password:
          type: string

    Authenticated:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string

    Book:
      type: object
      required:
        - title
        - borrowDate
        - returnDate
      properties:
        title:
          type: string
          maximum: 50
        borrowDate:
          type: string
          format: date
        returnDate:
          type: string
          format: date

    UserRole:
      type: string
      enum: [ADMIN, COMMON]

    User:
      type: object
      required:
        - role
      properties:
        role:
          oneOf:
            - $ref: "#/components/schemas/UserRole"

    BadRequestError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        reason:
          type: string

  parameters:
    BookListParams:
      in: query
      name: title
      required: true
      schema:
        type: string

  responses:
    ValidUser:
      description: ""
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"
          examples:
            default:
              $ref: "#/components/examples/me200"

    LoginSuccess:
      description: ""
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Authenticated"

    BookSuccess:
      description: ""
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
                - $ref: "#/components/schemas/Id"
                - $ref: "#/components/schemas/Book"

    BadRequest:
      description: ""
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/BadRequestError"

  requestBodies:
    Login:
      description: ""
      content:
        application/json:
          schema:
            required:
              - email
              - password
            allOf:
              - $ref: "#/components/schemas/Email"
              - $ref: "#/components/schemas/Password"
    Book:
      description: ""
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Book"

  examples:
    me200:
      value:
        - role: "ADMIN"
