# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: check lint

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      # TODO: 高速化したくなったらactions/cacheでnode_modulesをcache
      - name: cache module
        uses: ./.github/actions/setup-node
      - name: run lint
        run: |
          npm run lint
        env:
          NODE_ENV: production
