# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: check lint

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      # TODO: 高速化したくなったらactions/cacheでnode_modulesをcache
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: cache node-modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: clean-install if cache-hit
        shell: bash
        run: |
          if [ "${{ steps.cache-node-modules.outputs.cache-hit }}" = "true" ]; then
            echo "skip npm clean-install"
          else
            npm ci
          fi

      - name: run lint
        run: |
          npm run lint
        env:
          NODE_ENV: production
