name: Install Module And Cache

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  cache:
    # if: github.event.pull_request.merged == true
    name: Cache NodeModules
    runs-on: ubuntu-latest
      
    steps:
      - uses: ./.github/actions/setup-node
        name: cache module