name: Run Tests

on:
  pull_request:
    types:
      # draftからPRレビューに変わったとき
      - ready_for_review
      - synchronize
  # push:
  #   branches: ["main"]

  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm playwright -V | awk '{ print $2 }')
          echo Playwright Version is $PLAYWRIGHT_VERSION
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Setup Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
          restore-keys: ${{ runner.os }}-playwright-cache-
        id: playwright-cache

      - name: Install Playwright
        run: |
          pnpm playwright install --with-deps &&
          pnpm playwright install-deps

      - name: Tests
        run: pnpm test:unit
