name: Unit Tests

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  #     - ready_for_review

jobs:
  test:
    # if: github.event.pull_request.draft == false
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Run Test
        run: pnpm test:unit
